# Generated by Django 4.2 on 2023-10-04 20:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('bug_type', models.CharField(choices=[('error', 'Error'), ('feature', 'New Feature'), ('enhancement', 'Enhancement'), ('other', 'Other')], default='error', max_length=35)),
                ('report_date', models.DateField(default=datetime.datetime.now)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done')], default='todo', max_length=35)),
            ],
        ),
    ]
