# Generated by Django 4.2 on 2023-10-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0002_auto_20231004_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
